### ISSUE TITLE
bug: race

### ISSUE THREAD

**Issue by joerg-christian** [AlpineMapsOrg/renderer#125]
Assertion failed: s_instance, file app/TimerFrontendManager.cpp, line 41

https://github.com/AlpineMapsOrg/renderer/blob/079f74a8a195e76def986645bddba501a5ade14e/app/TimerFrontendManager.cpp#L41

**Comment by adam-ce** [comment]
fixed on next branch in 789d27d52695231eb42f6a77e0ba60426d01e24c
