### ISSUE TITLE
Deploy for Desktop

### ISSUE THREAD

**Issue by GeraldKimmersdorfer** [AlpineMapsOrg/renderer#53]
Currently I do the following steps, when i want to create an executable for Windows:

- Change path inside ShaderProgram.cpp (ALP_RESOURCES_PREFIX => "shaders/")
- Change path inside app/main.cpp:
  - HotReloader hotreloader(&engine, ALP_QML_SOURCE_DIR); => HotReloader hotreloader(&engine, "app/");
  - engine.load(QUrl(ALP_QML_SOURCE_DIR "main_loader.qml")); => engine.load(QUrl("app/main_loader.qml"));
- build exe
- copy created files into seperate folder
- run: windeployqt --qmldir app alpineapp.exe
- copy shaders folder from source/gl_engine inside executable directory

This information could be useful for others so I'm gonna park it here (maybe intersting in Readme.md?) But in general it should be possible and it would be cool to be able to deploy using cmake somehow.

**Comment by adam-ce** [comment]
we are already deploying the webassembly using cmake (at least partly, i'm still making some changes in the html file every time). this is perfectly doable. we can even pack it into a ci step and have an zip built automatically.

**Comment by adam-ce** [comment]
i don't think this has a high priority, and i don't think anybody would have time for it, ever. so closing the issue :)
