### ISSUE TITLE
Multi-threaded on alpinemaps.org

### ISSUE THREAD

**Issue by GeraldKimmersdorfer** [AlpineMapsOrg/renderer#66]
It would be beneficial if the web version on alpinemaps.org would be the multithreaded version, as you can very clearly tell the difference in speed.

I know that some devices don't support it, but maybe a Javascript-Script could determine support on website load and initialize the multithreaded version if possible.

**Comment by adam-ce** [comment]
i agree. but somebody would have to implement that :)

this is imo the same bug as #35, so closing it as duplicate. but i'll steal the title as it's more fitting :)

**Comment by adam-ce** [comment]
and i'd like to add, that i would want to avoid excluding more clients, as this will make it harder and harder to demo to people. we should fix the bugs instead :)
